// <auto-generated />
namespace FinalPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Tipo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Tipo));
        
        string IMigrationMetadata.Id
        {
            get { return "202302120048411_Tipo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
